Coding-Coach/find-a-mentor-api

- src/modules/mentors/dto/mentorfilters.dto.ts
- src/modules/mentors/mentors.controller.ts
- src/modules/mentors/mentors.service.ts
- src/modules/mentors/schema/mentorrequest.schema.ts
> Filtering mentors by tags, country, name and language

- .env.example
- README.md
Closes #8
Also added brief instructions to the `installation` section of the `README`.
> add example env file

- src/modules/mentors/interfaces/application.interface.ts
- src/modules/mentors/mentors.controller.ts
- src/modules/mentors/mentors.service.ts
- src/modules/users/users.controller.ts
Adds an endpoint to retrieve (for admins only) the list of applications filtered by status
Closes #11
> Retrieving applications

- src/middlewares/auth.middleware.ts
- src/modules/mentors/dto/application.dto.ts
- src/modules/mentors/interfaces/application.interface.ts
- src/modules/mentors/mentors.controller.ts
- src/modules/mentors/mentors.service.ts
- src/modules/users/dto/user.dto.ts
- src/modules/users/interfaces/user.interface.ts
- src/modules/users/schemas/user.schema.ts
- src/modules/users/users.controller.ts
- src/modules/users/users.service.ts
Once users submit their application to become mentors, admin users can now approve them and add the `Mentor` role to the user.
We need to allow admins to reject the application, for this we need to define the process and the scenarios.
closes #12
> Approving a mentor

- package.json
- scripts/addroles.js
> Creating script to update user roles from the terminal

- src/middlewares/auth.middleware.ts
- src/modules/mentors/mentors.controller.ts
> Setting up public endpoints

- src/modules/users/dto/user.dto.ts
- src/modules/users/users.controller.ts
Fixing validations where users were able to save any object in some fields
closes #23
> Fix validations

- src/modules/mentors/dto/application.dto.ts
- src/modules/mentors/interfaces/application.interface.ts
- src/modules/mentors/mentors.controller.ts
- src/modules/mentors/mentors.service.ts
- src/modules/mentors/schemas/application.schema.ts
- src/modules/users/users.controller.ts
Endpoint now approves or rejects applications
closes #22
> Rejecting applications

- package.json
- yarn.lock
Upgrading libraries to avoid security issues warning
> Fixing security issues with dependencies

- src/middlewares/auth.middleware.ts
- src/modules/mentors/mentors.controller.ts
- src/modules/mentors/mentors.service.ts
- src/modules/users/dto/user.dto.ts
We want users to sign in in order to contact mentors, therefore this PR removes the channels array for non authenticated users
Closes #29
> Remove channels from  unauthenticated users

- package.json
- yarn.lock
> Fixing build

- src/modules/users/dto/user.dto.ts
- src/modules/users/schemas/user.schema.ts
> make user field required

- docker-compose-db.yml
- docker-compose.yml
- package.json
- scripts/import-mentors.ts
This PR should allow to import  the `mentors.json` file as specified in #26.
However, during the cleanup of the script I broke something and now the users are no longer written to mongo. As I'm still quite new to javascript, I could not yet figure out, why the `user.save()` function is no longer working properly.
I hope someone can point me to the problem I'm facing.
Thanks
> Import mentors

- package.json
- scripts/import-mentors.ts
Adding member role to imported mentors
> Adding member role

- src/modules/users/users.controller.ts
- src/modules/users/users.service.ts
- src/utils/objectid.ts
- tsconfig.json
When deleting an existing user the validation was wrong and always returning 401 errors.
Also fixed another issue when signing up new existing mentors, there was an issue where the returned data was wrong.
Closes #46
> [FIX] Fixing bug when deleting account

- src/modules/common/mentors.service.ts
- src/modules/email/email.service.ts
- src/modules/mentors/mentors.controller.ts
> Return all user's data for each application

- src/modules/mentors/mentors.controller.ts
Return applications for the given user by adding a new endpoint:
```
GET /mentors/:user_id/applications
```
> Returning applications for the given user

- package-lock.json
- src/utils/request.d.ts
- tsconfig.json
Typescript is failing when building the app:
```
src/modules/users/users.controller.ts:123:73 - error TS2339: Property 'user' does not exist on type 'Request'.
123     const current: User = await this.usersService.findByAuth0Id(request.user.auth0Id);
~~~~
src/modules/users/users.controller.ts:158:73 - error TS2339: Property 'user' does not exist on type 'Request'.
158     const current: User = await this.usersService.findByAuth0Id(request.user.auth0Id);
```
This PR adds the `User` type to the request object.
> [FIX] Express user type

- src/middlewares/auth.middleware.ts
- tsconfig.json
Fixing the build once and for all!
> Disabling the warning for assigning the auth0 id in the middleware

- src/main.ts
- src/modules/common/pipes/pagination.pipe.ts
Fixing pagination per page and removing docs from production
> Removing docs from production

- README.md
> Adding travis build status icon

- package.json
- src/modules/common/auth0.service.ts
- src/modules/common/common.module.ts
- src/modules/common/users.service.ts
- src/modules/users/__tests__/users.controller.spec.ts
- src/modules/users/users.controller.ts
- yarn.lock
When removing an user from our systems we also need to remove the user from auth0, this will prevent the user to login again, once removed
I've created a common service to deal with auth0, this will allow us to reuse existing functionality such as getting a new token. I also added unit tests for the new functionality 🎉
closes #80
> Removing user from auth0

- CONTRIBUTING.md
- README.md
This PR adds a guide showing how to setup the project in your local environment, this will allow contributors to easily run the app.
closes #42
> Adding a Contribute guide

- package.json
- src/config/index.ts
- src/main.ts
- src/modules/users/users.controller.ts
- yarn.lock
Closes #82 
Add, initialize and configure sentry with user info whenever it's present.
You can get the sentry `DSN` from the settings on their website or I can send it in DM.
> Add sentry

- src/modules/common/dto/application.dto.ts
☝️ What it says in the tin.
closes #101
> Set max length to 400

- src/modules/lists/favorites.controller.ts
> Fixing favorites removal

- src/modules/lists/__tests__/favorites.controller.spec.ts
- src/modules/lists/favorites.controller.ts
Returning an empty list object when no favorites list is created by the current user
> Returning an empty list

- src/modules/common/dto/mentorfilters.dto.ts
- src/modules/common/interfaces/user.interface.ts
- src/modules/common/mentors.service.ts
- src/modules/mentors/__tests__/mentors.controller.spec.ts
- src/modules/mentors/mentors.controller.ts
When a mentor is not available we want to hide the channels from users
closes #119
> Hiding channels for unavailable mentors

- src/modules/common/dto/user.dto.ts
- src/modules/common/interfaces/user.interface.ts
> Fixes #129

- src/modules/mentorships/interfaces/mentorship.interface.ts
> Add cancelled status to the mentorship interface

- src/modules/mentorships/schemas/mentorship.schema.ts
Ref: https://mongoosejs.com/docs/api.html#schemastringoptions_SchemaStringOptions-enum
> Add enum validation to the mentorship status field

- .travis.yml
> Run E2E tests in CI

- docker-compose.yml
Bumps docker node version from 8-alpine to 12.20.1-alpine
Target: #178
> bump docker node version

- src/modules/lists/favorites.controller.ts
- src/modules/lists/lists.controller.ts
- src/modules/mentors/mentors.controller.ts
- src/modules/mentorships/mentorships.controller.ts
- src/modules/users/users.controller.ts
Follow-up of https://github.com/Coding-Coach/find-a-mentor-api/pull/174
> Refactor controllers to await independent promises using `Promise.all`

- src/modules/mentorships/__tests__/mentorships.controller.spec.ts
- src/modules/mentorships/dto/mentorshipUpdatePayload.dto.ts
- src/modules/mentorships/interfaces/mentorship.interface.ts
- src/modules/mentorships/mentorships.controller.ts
> fix(mentorships): filter deleted users

- src/modules/mentorships/dto/mentorship.dto.ts
Related https://github.com/Coding-Coach/find-a-mentor/issues/778
> fix(mentorship-request): increase fields limits

- content/email_templates/README.md
- content/email_templates/mentorship-cancelled.html
- src/modules/email/interfaces/email.interface.ts
- src/modules/mentorships/mentorships.controller.ts
- test/api/mentorships.e2e-spec.ts
> feat: cancel mentorship email

- content/email_templates/README.md
- content/email_templates/layout.html
- content/email_templates/mentor-application-approved.html
- content/email_templates/mentor-application-declined.html
- content/email_templates/mentor-application-received.html
- content/email_templates/mentor-freeze.html
- content/email_templates/mentor-not-active.html
- content/email_templates/mentorship-accepted.html
- content/email_templates/mentorship-cancelled.html
- content/email_templates/mentorship-declined.html
- content/email_templates/mentorship-reminder.html
- content/email_templates/mentorship-requested.html
- content/email_templates/show.js
- content/email_templates/welcome.html
- package.json
- src/modules/common/users.service.ts
- src/modules/email/email.service.ts
- src/modules/email/interfaces/email.interface.ts
- yarn.lock
> core(emails): use ejs

- src/modules/admin/admin.controller.ts
Currently the admin can't start the mentor inactive flow if the mentors responded at any point.
This PR aims to allow the mentor to start the flow if last action was more than a month ago
> feat: inactive mentor in the last month

- src/modules/mentorships/mentorships.controller.ts
- src/modules/mentorships/mentorships.service.ts
- test/api/mentorships.e2e-spec.ts
> feat(accepted-mentorships-email): add open requests

- content/email_templates/README.md
- content/email_templates/mentorship-requested.html
- src/modules/email/interfaces/email.interface.ts
- src/modules/mentorships/mentorships.controller.ts
> feat(email): mentorship requested include background + expectations

- src/modules/email/interfaces/email.interface.ts
- src/modules/mentorships/mentorships.controller.ts
mentorships controller (mentorship-requested email to mentor)
> Adds menteeEmail in type MentorshipRequested and mentorships controller

- src/modules/common/dto/user.dto.ts
- src/modules/users/users.controller.ts
Related client task - https://github.com/Coding-Coach/find-a-mentor/issues/852
> feat: extend user description and tags

- content/email_templates/README.md
- content/email_templates/mentorship-declined.html
- src/modules/admin/admin.controller.ts
- src/modules/email/interfaces/email.interface.ts
- src/modules/mentorships/mentorships.controller.ts
> feat: decline open requests when freezing mentor

- src/modules/mentorships/__tests__/mentorships.controller.spec.ts
- src/modules/mentorships/mentorships.controller.ts
- src/modules/mentorships/mentorships.service.ts
- test/api/mentorships.e2e-spec.ts
> feat(mentorship): limit allowed open requests
